### ISSUE TITLE
Is it fair to add all the class labels to vocabulary from both Visual Genome and Open Images?

### ISSUE THREAD

**Issue by Vimos** [nocaps-org/updown-baseline#2]
In the baseline code, the vocab is generated from only COCO training dataset. If we need out-of-domain class label words, is it fair to add them to vocabulary?

**Comment by mkumar10** [comment]
+1

**Comment by kdexd** [comment]
yes, it is fair to add those labels to the vocabulary — however, we avoid them specifically for our baseline, because we establish the performance of a well-performing model on COCO, on `nocaps`.

Intuitively, I wonder if it could help directly, as those words are absent in the caption corpus, their input embeddings would not change after random init, and their output embeddings would have a large negative bias term after convergence.
